CREATE TABLE CHASSIS (
    ID INT PRIMARY KEY,
    SOURCE_STATUS VARCHAR(100) NOT NULL,
    ARCHIVED_TIME TIMESTAMP(3) WITHOUT TIME ZONE,
    DELETE_TIME TIMESTAMP(3) WITHOUT TIME ZONE
);

CREATE TABLE ENGLISH_STATEMENT (
    ID INT PRIMARY KEY,
    CHASSIS_ID INT REFERENCES CHASSIS(ID),
    SOURCE_STATUS VARCHAR(100) NOT NULL,
    PARENT_ARCHIVED_TIME TIMESTAMP(3) WITHOUT TIME ZONE,
    DELETE_TIME TIMESTAMP(3) WITHOUT TIME ZONE
);

INSERT INTO CHASSIS(ID, SOURCE_STATUS, ARCHIVED_TIME, DELETE_TIME)
VALUES (1, 'ARCHIVED', '2026-02-09 15:30:00.100', '2026-02-09 15:30:00.000')
ON CONFLICT(ID)
DO UPDATE SET
    SOURCE_STATUS = EXCLUDED.SOURCE_STATUS
WHERE 
    CHASSIS.SOURCE_STATUS='DELETED' AND EXCLUDED.SOURCE_STATUS='ARCHIVED'
;

INSERT INTO ENGLISH_STATEMENT(ID, CHASSIS_ID, SOURCE_STATUS, PARENT_ARCHIVED_TIME, DELETE_TIME)
VALUES (1, 1, 'DELETED', NULL, '2026-02-09 15:30:01.200');
INSERT INTO ENGLISH_STATEMENT(ID, CHASSIS_ID, SOURCE_STATUS, PARENT_ARCHIVED_TIME, DELETE_TIME)
VALUES (2, 1, 'DELETED', NULL, '2026-02-09 15:30:01.300');
INSERT INTO ENGLISH_STATEMENT(ID, CHASSIS_ID, SOURCE_STATUS, PARENT_ARCHIVED_TIME, DELETE_TIME)
VALUES (3, 1, 'DELETED', NULL, '2026-02-08 15:30:00.000');

BEGIN;
    UPDATE CHASSIS
    SET SOURCE_STATUS = 'ARCHIVED'
    WHERE ID = 1;

    UPDATE ENGLISH_STATEMENT
    SET SOURCE_STATUS = 'ARCHIVED', PARENT_ARCHIVED_TIME = CHASSIS.ARCHIVED_TIME
    FROM CHASSIS
    WHERE ENGLISH_STATEMENT.CHASSIS_ID = CHASSIS.ID AND CHASSIS.ARCHIVED_TIME - ENGLISH_STATEMENT.DELETE_TIME < INTERVAL '1 days'
    AND CHASSIS.ID = 1;

    DELETE FROM ENGLISH_STATEMENT
    WHERE ENGLISH_STATEMENT.CHASSIS_ID = CHASSIS.ID AND CHASSIS.ARCHIVED_TIME - ENGLISH_STATEMENT.DELETE_TIME > INTERVAL '1 days'
    AND CHASSIS.ID = 1;
COMMIT;

TRUNCATE TABLE CHASSIS;
TRUNCATE TABLE ENGLISH_STATEMENT;