CREATE TABLE SUPPLIER (
    SUPPLIER_ID INT PRIMARY KEY,
    SUPPLIER_NUMBER VARCHAR(255),
    SUPPLIER_NAME VARCHAR(255),
    IS_LOCKED BOOLEAN,
    LOAD_DATE_TIME TIMESTAMP(3) WITHOUT TIME ZONE,
    UPDATE_DATE_TIME TIMESTAMP(3) WITHOUT TIME ZONE
);

INSERT INTO SUPPLIER(SUPPLIER_ID, SUPPLIER_NUMBER, SUPPLIER_NAME, IS_LOCKED, LOAD_DATE_TIME, UPDATE_DATE_TIME)
VALUES (1, 'number_1', 'name_1', FALSE, '2023-01-01T00:00:00Z', '2023-01-01T00:00:00.300')
ON CONFLICT(SUPPLIER_ID)
DO UPDATE SET
    SUPPLIER_NUMBER=EXCLUDED.SUPPLIER_NUMBER,
    SUPPLIER_NAME=EXCLUDED.SUPPLIER_NAME,
    IS_LOCKED=EXCLUDED.IS_LOCKED,
    UPDATE_DATE_TIME=EXCLUDED.UPDATE_DATE_TIME
WHERE 
    SUPPLIER.UPDATE_DATE_TIME < EXCLUDED.UPDATE_DATE_TIME
RETURNING *;

select * from SUPPLIER;

delete from SUPPLIER;

DROP TABLE IF EXISTS SUPPLIER;