kafka_consumer_config:
  bootstrap.servers": localhost:9092
  auto.offset.reset": latest
  enable.auto.commit": true
  
topics:
  - topic: "leyland_topic"
    consumer_group: 'leyland_consumer_group'
    standardization_mapping_file: "schema_standardization/leyland_mapping.yaml"

  - topic: "australia_topic"
    consumer_group: "australia_consumer_group"
    standardization_mapping_file: "schema_standardization/australia_mapping.yaml"